name: React CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Change to client directory
        run: |
          cd client
          echo "Changed directory to $(pwd)"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.15.1'

      - name: Install dependencies
        run: |
          cd client
          echo "Installing dependencies in $(pwd)"
          npm install

      - name: Run ESLint
        run: |
          cd client
          echo "Running ESLint in $(pwd)"
          npm run lint

      - name: Run Tests
        run: |
          cd client
          echo "Running tests in $(pwd)"
          npm test
