name: React CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.15.1"

      - name: Install dependencies
        run: |
          cd client
          echo "Installing dependencies in $(pwd)"
          npm install

      - name: Run ESLint
        run: |
          cd client
          echo "Running ESLint in $(pwd)"
          npm run lint

      - name: Run Type-Check
        run: |
          cd client
          echo "Running Type-Check in $(pwd)"
          npm run typeCheck

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.15.1"

      - name: Install dependencies
        run: |
          cd client
          npm install

      - name: Build React app
        run: |
          cd client
          npm run build
          echo "Current working directory:"
          pwd
          echo "Contents of current directory:"
          ls

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Deploy to S3
        env:
          S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        run: |
          aws s3 sync client/dist s3://$S3_BUCKET --delete
