name: React CI/CD

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Change to client directory
        run: |
          cd client
          echo "Changed directory to $(pwd)"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.15.1'

      - name: Install dependencies
        run: |
          cd client
          echo "Installing dependencies in $(pwd)"
          npm install

      - name: Run ESLint
        run: |
          cd client
          echo "Running ESLint in $(pwd)"
          npm run lint

      - name: Run Tests
        run: |
          cd client
          echo "Running tests in $(pwd)"
          npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.15.1'
  
      - name: Install dependencies
        run: |
          cd client
          npm install

      - name: Build React app
        run: |
          cd client
          npm run build
          echo "Current working directory:"
          pwd
          echo "Contents of current directory:"
          ls
  
      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region us-west-1
  
      - name: Deploy to S3
        env:
          S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        run: |
          aws s3 sync client/build s3://$S3_BUCKET --delete
