# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: Spring CI

on:
  push:
    branches:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Change to server directory
        run: |
          cd server
          echo "Changed directory to $(pwd)"

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        run: |
          cd server
          mvn -B package --file pom.xml

      - name: Run Tests with Maven
        run: |
          cd server 
          mvn -B test --file pom.xml
